# deploy Maven artifacts to Sonatype OSS repo
language: java

jdk:
  - openjdk6

# whitelist
branches:
  only:
    - master

# checkout settings
before_install: 
  - "git clone -b master https://github.com/molindo/travis-settings.git target/travis-settings"
  - "target/travis-settings/tasks/before_install.sh"

# install and deploy
install: "target/travis-settings/tasks/install.sh"
script:  "target/travis-settings/tasks/script.sh"

# travis encrypt 'token@room'
notifications:
  email: false
  hipchat: 
    rooms:
      - secure: "fehcwcG4g3ifm3XzGYfhHLQE4EE3mWhkp5zyt3eNPTNYfsmubyR8c2MpK+EFn1dXknsiuAtqbJdO2QHvH7jceIa3dQ+ge6+f7eUvO22aFJBj3nrJuRSc38CuxSBJpmmwLinVEYVpTqTJuSxmJ7+HCRqtZwaQkpeW0NHAe39s9KE="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    on_success: always
    on_failure: always

# travis encrypt 'CI_DEPLOY_USERNAME=username'
# travis encrypt 'CI_DEPLOY_PASSWORD=password'
# travis encrypt 'AMAZON_KEY=key'
# travis encrypt 'AMAZON_SECRET=secret'
env:
  global:
    - secure: "GcO+8wr6dOrtUKweW9dJj1n8UA8+X6FcDwGvqiLKRnYmmeYWTTnqZi44forqXUK1gZPdEPg9bNoLpMGdZfXYryesaNjmt5JYLSK9gvjAJx5/cR8C4D1fcvdwZ5pKlB+t1hu5XBXxXIFbYhY3HwB7b9hSJJ8pvXRoSvzJH0GXTW4="
    - secure: "F/KxdplGKcYi0kZZ+9i7vehJZD05KG0SStnv6ROUA4pVIg0GtmY5tpk6LuZ8e/mlJxToOHF5Y/KRlHWYqnmuigDaBOTqI28wnO2SonWPoNYlHPToj6WFXbz3Gbl1aB6c05luiQ4jZ/I1jAoIYp13NLKJ5x0x8iPspfOWNVYlYqo="
    - secure: "FbiPdY8UK4D2ldntnY7GTjzyAwYOhUFQqihXjYR5ViQsImojVlk8CK4EZ6L7Qd/2Gdg8iYrJBg3fin0kAluejzA68fvDcFS8M9NlojDGcAfb2rHUcOW8wyT50poEjLXmvjX2WerOlayIZB9OBkZL5nC6zZoKh/xgT
    - secure: "SMkzUr0Jaw5dVzrNXiazNTtFUHKSa0Y5lxH3JcZMjZhUlzV/TmXQ5N3JeX2TVtVu2ZXCGJWJuA5tXoZGYjElgEpcUOxQGJVHwLwTuI/B39Gl/Sr+MroWUWQx+kjUjX2jpcXppylxr3UXSlBuFFHCUHXNSL6rzN9ll

